# Generated by Django 4.1.7 on 2023-03-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('package', models.IntegerField(max_length=200, null=True)),
                ('experience_in_yrs', models.IntegerField(max_length=200, null=True)),
            ],
        ),
    ]
