# Generated by Django 4.1.7 on 2023-03-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisations',
            name='package',
        ),
        migrations.AddField(
            model_name='organisations',
            name='package_in_yrs',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
