# Generated by Django 4.1.7 on 2023-03-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_organisations_package_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisations',
            old_name='package_in_yrs',
            new_name='package_in_LPA',
        ),
    ]
