# Generated by Django 4.1.7 on 2023-03-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_package_in_yrs_organisations_package_in_lpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
