# Generated by Django 4.1.7 on 2023-03-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='vacancies',
            field=models.IntegerField(choices=[(-15, 'few'), (-34, 'high'), (-49, 'alot'), (-900, 'mass')], max_length=200, null=True),
        ),
    ]
