# Generated by Django 4.1.7 on 2023-03-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_organisations_vacancies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organisations',
            table='organisations',
        ),
    ]
