# Generated by Django 4.1.7 on 2023-03-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_organisations_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='vacancies',
            field=models.CharField(choices=[('0-15', 'few'), ('16-50', 'high'), ('51-100', 'alot'), ('100-1000', 'mass')], max_length=200, null=True),
        ),
    ]
