# Generated by Django 4.1.7 on 2023-03-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_organisations_vacancies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='registration',
        ),
    ]
